import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL = 'https://ilkfwfoxqrlmjficefer.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_hQdAtV79QuzoxqK1rTYmHg_vNj5Pnz8';
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, { auth: { persistSession:false, autoRefreshToken:false, detectSessionInUrl:false } });
const $ = s => document.querySelector(s);
const lobbyScreen=$('#lobby-screen'), waitingScreen=$('#waiting-screen'), gameScreen=$('#game-screen'), joinButton=$('#join-button');
function getPlayerId(){ try{ if(typeof window.name==='string'&&window.name.startsWith('duel:'))return window.name.slice(5); const id=crypto.randomUUID(); try{window.name=`duel:${id}`;}catch(_){} return id;}catch(_){return crypto.randomUUID();} }
const playerId=getPlayerId();
let currentRoom=null,roomChannel=null,actionChannel=null,myAction=null,timerInterval=null,heartbeatInterval=null,lastLoggedTurn=0,resolving=false;
const ROOM_STALE_MS=20000,MAX_HP=100,ACTIONS=['attack','defend','counter','heal','advanced'];
const ACTION_LABELS={attack:'공격',defend:'방어',counter:'역공',heal:'회복',advanced:'고급행동'};
function makePlayer(id,name){return{id,name,hp:100,luck:0,luckBoostTurns:0,bleed:0,bleedTurns:0,invincible:0,shield:0,stun:0,confusion:0,advancedBlock:0,basicDebuff:0,rest:0};}
function initialState(room){return{players:{[room.player1_id]:makePlayer(room.player1_id,room.player1_name),[room.player2_id]:makePlayer(room.player2_id,room.player2_name)},turn:1,phase:'playing',winnerId:null,lastResult:'전투 시작!'};}
function myPlayer(state){return state.players[playerId];} function enemyPlayer(state){return Object.values(state.players).find(p=>p.id!==playerId);} function isHost(){return currentRoom?.player1_id===playerId;} function isStale(t){return !t||Date.now()-new Date(t).getTime()>ROOM_STALE_MS;} function clamp(n,a,b){return Math.max(a,Math.min(b,n));} function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a;} function chance(p){return Math.random()*100<p;}
function showWaiting(message){$('#waiting-room-code').textContent=currentRoom?.room_code??$('#room-code').value;$('#waiting-status').textContent=message;lobbyScreen.classList.add('hidden');gameScreen.classList.add('hidden');waitingScreen.classList.remove('hidden');}
function showGame(state){lobbyScreen.classList.add('hidden');waitingScreen.classList.add('hidden');gameScreen.classList.remove('hidden');renderState(state);}
function formatStatus(p){if(!p)return'';const x=[`운 ${p.luck}%`];if(p.bleedTurns)x.push(`출혈 ${p.bleed} (${p.bleedTurns}턴)`);if(p.invincible)x.push(`무적 ${p.invincible}턴`);if(p.shield)x.push(`보호막 ${p.shield}턴`);if(p.stun)x.push(`스턴 ${p.stun}턴`);if(p.confusion)x.push(`혼란 ${p.confusion}턴`);if(p.advancedBlock)x.push(`고급행동 금지 ${p.advancedBlock}턴`);if(p.basicDebuff)x.push(`기본행동 약화 ${p.basicDebuff}턴`);if(p.rest)x.push(`휴식 ${p.rest}턴`);return x.map(v=>`<span class="status">${v}</span>`).join('');}
function renderState(state){if(!state?.players?.[playerId])return;const me=myPlayer(state),enemy=enemyPlayer(state);$('#my-name').textContent=me.name;$('#enemy-name').textContent=enemy?.name??'상대';$('#my-hp').style.width=`${clamp(me.hp,0,100)}%`;$('#enemy-hp').style.width=`${clamp(enemy?.hp??0,0,100)}%`;$('#my-hp-text').textContent=`${Math.max(0,me.hp)} / ${MAX_HP}`;$('#enemy-hp-text').textContent=`${Math.max(0,enemy?.hp??0)} / ${MAX_HP}`;$('#my-status').innerHTML=formatStatus(me);$('#enemy-status').innerHTML=formatStatus(enemy);$('#turn-number').textContent=`턴 ${state.turn}`;$('#turn-status').textContent=state.phase==='finished'?'전투 종료':(myAction?`선택 완료: ${ACTION_LABELS[myAction]} — 상대를 기다리는 중`:'행동을 선택하세요.');updateButtons(state);}
function addLog(text){const log=$('#battle-log-list');if(!log||!text)return;const p=document.createElement('p');p.textContent=text;log.appendChild(p);log.scrollTop=log.scrollHeight;}
function updateButtons(state){const me=myPlayer(state);document.querySelectorAll('[data-action]').forEach(b=>{let d=state.phase==='finished'||Boolean(myAction)||!me||me.stun>0||me.rest>0;if(b.dataset.action==='advanced'&&me?.advancedBlock>0)d=true;b.disabled=d;});}
function startTimer(startedAt){clearInterval(timerInterval);if(!startedAt){$('#timer').textContent='5';return;}const end=new Date(startedAt).getTime()+5000;const tick=()=>{const left=Math.max(0,end-Date.now());$('#timer').textContent=String(Math.ceil(left/1000));if(left<=0){clearInterval(timerInterval);checkForResolution();}};tick();timerInterval=setInterval(tick,100);}
async function heartbeat(){if(!currentRoom?.room_code)return;const now=new Date().toISOString();let q=supabase.from('rooms').update({... (currentRoom.player1_id===playerId?{player1_seen_at:now}:{}),...(currentRoom.player2_id===playerId?{player2_seen_at:now}:{})}).eq('room_code',currentRoom.room_code);if(currentRoom.player1_id===playerId)q=q.eq('player1_id',playerId);else if(currentRoom.player2_id===playerId)q=q.eq('player2_id',playerId);const{data,error}=await q.select().maybeSingle();if(!error&&data)currentRoom=data;}
function startHeartbeat(){clearInterval(heartbeatInterval);heartbeat();heartbeatInterval=setInterval(heartbeat,5000);}
async function ensureGameStarted(){if(!currentRoom?.player1_id||!currentRoom?.player2_id)return;if(currentRoom.status==='starting'&&isHost()&&!currentRoom.game_state){const state=initialState(currentRoom);const{data,error}=await supabase.from('rooms').update({status:'playing',game_state:state,turn:1,turn_started_at:new Date().toISOString()}).eq('room_code',currentRoom.room_code).select().single();if(error){console.error(error);return;}currentRoom=data;}if(currentRoom.status==='starting')showWaiting('상대가 입장했습니다. 잠시 후 시작합니다!');if((currentRoom.status==='playing'||currentRoom.status==='finished')&&currentRoom.game_state){showGame(currentRoom.game_state);startTimer(currentRoom.turn_started_at);}}
async function resetRoomForNewPlayer(existing,name){await supabase.from('game_actions').delete().eq('room_code',existing.room_code);const{data,error}=await supabase.from('rooms').update({player1_name:name,player1_id:playerId,player1_seen_at:new Date().toISOString(),player2_name:null,player2_id:null,player2_seen_at:null,status:'waiting',game_state:null,turn:1,turn_started_at:null,winner_id:null,winner_name:null}).eq('room_code',existing.room_code).select().single();if(error)throw error;return data;}
async function joinRoom(){const name=$('#player-name').value.trim(),roomCode=$('#room-code').value.trim();if(!name)return alert('이름을 입력해주세요.');if(!/^\d{4}$/.test(roomCode))return alert('방번호는 4자리 숫자로 입력해주세요.');joinButton.disabled=true;try{const{data:existing,error:findError}=await supabase.from('rooms').select('*').eq('room_code',roomCode).maybeSingle();if(findError)throw findError;const now=new Date().toISOString();if(!existing){const{data,error}=await supabase.from('rooms').insert({room_code:roomCode,player1_name:name,player1_id:playerId,player1_seen_at:now,status:'waiting'}).select().single();if(error)throw error;currentRoom=data;showWaiting('상대를 기다리는 중...');}else if(existing.status==='finished'){currentRoom=await resetRoomForNewPlayer(existing,name);showWaiting('새 대전을 준비하는 중...');}else if(existing.player1_id===playerId){const{data,error}=await supabase.from('rooms').update({player1_name:name,player1_seen_at:now}).eq('room_code',roomCode).select().single();if(error)throw error;currentRoom=data;if(currentRoom.player2_id)await ensureGameStarted();else showWaiting('상대를 기다리는 중...');}else if(existing.player2_id===playerId){const{data,error}=await supabase.from('rooms').update({player2_name:name,player2_seen_at:now}).eq('room_code',roomCode).select().single();if(error)throw error;currentRoom=data;await ensureGameStarted();}else if(isStale(existing.player1_seen_at)&&isStale(existing.player2_seen_at)){currentRoom=await resetRoomForNewPlayer(existing,name);showWaiting('오래된 방을 정리하고 새 방으로 시작합니다...');}else if(!existing.player2_id||isStale(existing.player2_seen_at)){const{data,error}=await supabase.from('rooms').update({player2_name:name,player2_id:playerId,player2_seen_at:now,status:'starting',game_state:null,turn:1,turn_started_at:null,winner_id:null,winner_name:null}).eq('room_code',roomCode).select().single();if(error)throw error;currentRoom=data;showWaiting('상대가 입장했습니다. 잠시 후 시작합니다!');}else return alert('현재 두 명이 플레이 중인 방입니다. 다른 방번호를 사용해주세요.');subscribe(roomCode);startHeartbeat();await ensureGameStarted();}catch(error){console.error(error);alert(`입장 오류: ${error.message??'Supabase 설정을 확인해주세요.'}`);}finally{joinButton.disabled=false;}}
function subscribe(roomCode){if(roomChannel)supabase.removeChannel(roomChannel);if(actionChannel)supabase.removeChannel(actionChannel);roomChannel=supabase.channel(`room-${roomCode}-${playerId}`).on('postgres_changes',{event:'*',schema:'public',table:'rooms',filter:`room_code=eq.${roomCode}`},async payload=>{if(payload.eventType==='DELETE')return;const previousTurn=currentRoom?.game_state?.turn;currentRoom=payload.new;if(currentRoom.game_state&&currentRoom.game_state.turn!==previousTurn){myAction=null;resolving=false;}if(currentRoom.game_state){showGame(currentRoom.game_state);startTimer(currentRoom.turn_started_at);if(currentRoom.game_state.lastResult&&currentRoom.game_state.turn!==lastLoggedTurn){addLog(currentRoom.game_state.lastResult);lastLoggedTurn=currentRoom.game_state.turn;}}else await ensureGameStarted();}).subscribe();actionChannel=supabase.channel(`actions-${roomCode}-${playerId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'game_actions',filter:`room_code=eq.${roomCode}`},async()=>{await checkForResolution();}).subscribe();}
function rollAttack(p){const luck=clamp(p.luck,0,100),bonus=Math.min(15,luck);let high=30+bonus,normal=50-Math.floor(bonus*.5);if(p.basicDebuff>0){high*=.85;normal*=.85;}const r=Math.random()*100;if(r<high)return{power:rand(16,30),label:'강공격'};if(r<high+normal)return{power:rand(5,15),label:'일반 공격'};return{power:0,label:'빗나감'};}
function rollDefense(p){return rand(0,Math.round(20+Math.min(5,p.luck/2)));}
function basicDamage(target,amount){if(amount<=0||target.invincible>0)return 0;const reduced=target.shield>0?Math.ceil(amount*.5):amount;target.hp=clamp(target.hp-reduced,0,MAX_HP);return reduced;}
function applyHeal(p){const amount=rand(0,12);p.hp=clamp(p.hp+amount,0,MAX_HP);let text=`${p.name} 회복 ${amount}`;if(chance(40)){p.luck=clamp(p.luck+10,0,100);p.luckBoostTurns=2;text+=', 운 상승!';}return text;}
function skillRoll(enemy){const r=Math.random()*100;if(enemy.hp<=30&&r<5)return'execute';if(r<20)return'vampire';if(r<35)return'stun';if(r<45)return'confusion';if(r<65)return'bleed';if(r<75)return'invincible';if(r<85)return'shield';return'rest';}
function applyAdvanced(me,enemy){if(!chance(55)){me.rest=1;return`${me.name} 고급행동 실패! 다음 턴 행동 불가`; }const skill=skillRoll(enemy);if(skill==='execute'){const d=basicDamage(enemy,Math.min(35,enemy.hp));return`${me.name} 처형! ${d} 피해`;}if(skill==='vampire'){const d=basicDamage(enemy,rand(10,25));me.hp=clamp(me.hp+d,0,MAX_HP);return`${me.name} 흡혈! ${d} 피해 및 ${d} 회복`;}if(skill==='stun'){enemy.stun=1;return`${me.name} 스턴! 상대는 다음 턴 행동 불가`;}if(skill==='confusion'){enemy.confusion=1;return`${me.name} 혼란! 상대의 다음 행동이 뒤섞임`;}if(skill==='bleed'){enemy.bleed=rand(3,7);enemy.bleedTurns=3;return`${me.name} 출혈 부여! 매 턴 ${enemy.bleed} 피해`;}if(skill==='invincible'){me.invincible=1;return`${me.name} 무적! 다음 공격 피해 무시`;}if(skill==='shield'){me.shield=1;return`${me.name} 보호막! 다음 피해 50% 감소`;}me.rest=1;return`${me.name} 휴식! 다음 턴 행동 불가`;}
function normalizeAction(a){return ACTIONS.includes(a)?a:null;}
async function chooseAction(action){if(!currentRoom?.game_state||resolving)return;const state=currentRoom.game_state,me=myPlayer(state);if(state.phase==='finished'||myAction||!me)return;if(me.stun>0||me.rest>0)return;action=normalizeAction(action);if(!action)return;myAction=action;updateButtons(state);const{error}=await supabase.from('game_actions').insert({room_code:currentRoom.room_code,turn:state.turn,player_id:playerId,action});if(error){myAction=null;updateButtons(state);alert(`행동 선택 오류: ${error.message}`);return;}await checkForResolution();}
async function checkForResolution(){if(resolving||!currentRoom?.game_state)return;const state=currentRoom.game_state;if(state.phase==='finished')return;const{data,error}=await supabase.from('game_actions').select('*').eq('room_code',currentRoom.room_code).eq('turn',state.turn);if(error)return;if(data?.length>=2||Date.now()-new Date(currentRoom.turn_started_at||Date.now()).getTime()>=5000){resolving=true;await resolveTurn(data||[]);}}
function processTurn(state,actions){const p1=state.players[state.players&&Object.keys(state.players)[0]],p2=state.players[state.players&&Object.keys(state.players)[1]];const map={};actions.forEach(a=>map[a.player_id]=a.action);const players=Object.values(state.players);if(players.length<2)return;let[a,b]=players;for(const p of players){if(p.bleedTurns>0){p.hp=clamp(p.hp-p.bleed,0,MAX_HP);p.bleedTurns--;if(p.bleedTurns===0)p.bleed=0;}if(p.luckBoostTurns>0)p.luckBoostTurns--;if(p.invincible>0)p.invincible--;if(p.shield>0)p.shield--;if(p.stun>0)p.stun--;if(p.confusion>0)p.confusion--;if(p.advancedBlock>0)p.advancedBlock--;if(p.basicDebuff>0)p.basicDebuff--;if(p.rest>0)p.rest--;}
const logs=[];const act=p=>map[p.id];for(const p of players){if(p.hp<=0)continue;let action=act(p);if(p.confusion>0&&action){const choices=ACTIONS.filter(x=>x!==action);action=choices[rand(0,choices.length-1)];}if(!action)action='rest';if(action==='attack'){const r=rollAttack(p);const enemy=players.find(x=>x!==p);const d=basicDamage(enemy,r.power);logs.push(d?`${p.name}의 ${r.label} → ${enemy.name} ${d} 피해`:`${p.name}의 공격이 빗나감`);}else if(action==='defend'){p.shield=1;logs.push(`${p.name} 방어`);}else if(action==='counter'){const enemy=players.find(x=>x!==p);if(chance(50)){const d=basicDamage(enemy,rand(8,18));logs.push(`${p.name} 역공 성공 → ${enemy.name} ${d} 피해`);}else logs.push(`${p.name} 역공 실패`);}else if(action==='heal')logs.push(applyHeal(p));else if(action==='advanced')logs.push(applyAdvanced(p,players.find(x=>x!==p)));}
for(const p of players)if(p.hp<=0){state.phase='finished';state.winnerId=players.find(x=>x.hp>0)?.id||null;}state.lastResult=logs.join(' | ')||'이번 턴에는 행동이 없었습니다.';if(state.phase!=='finished')state.turn++;}
async function resolveTurn(actions){try{if(!isHost())return;const state=JSON.parse(JSON.stringify(currentRoom.game_state));processTurn(state,actions);const update={game_state:state,turn:state.turn,turn_started_at:state.phase==='finished'?null:new Date().toISOString(),status:state.phase==='finished'?'finished':'playing',winner_id:state.winnerId,winner_name:state.winnerId?state.players[state.winnerId]?.name:null};const{data,error}=await supabase.from('rooms').update(update).eq('room_code',currentRoom.room_code).eq('turn',currentRoom.turn).select().single();if(error)console.error(error);else currentRoom=data;}finally{resolving=false;}}
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>chooseAction(b.dataset.action)));joinButton?.addEventListener('click',joinRoom);
